name: Deploy-web-application-war-file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
	build:
		runs-on: ubuntu-latest
			steps:
				-uses: actions/checkout@v3
				-name: Install Maven
				run: 
    				sudo apt-get install maven
			  	# Build WAR File
			  	mvn clean install

